name: Deploy Admin-Web to Azure Static Web Apps

# Trigger this workflow on pushes to main when files in apps/admin-web change,
# or when this workflow file itself is updated.
on:
  push:
    branches:
      - main
    paths:
      - 'apps/admin-web/**'
      - '.github/workflows/deploy-admin-web.yml'

# Permissions:
# - id-token: write (only needed for OIDC authentication flows)
# - contents: read (required for checkout)
permissions:
  id-token: write
  contents: read

jobs:
  deploy_admin_web:
    runs-on: ubuntu-latest

    # Environment variables for the Vite build
    env:
      # Azure AD integration values injected at build time
      VITE_AZURE_AD_CLIENT_ID:                ${{ secrets.VITE_AZURE_AD_CLIENT_ID }}
      VITE_AZURE_AD_TENANT_ID:                ${{ secrets.AZURE_AD_TENANT_ID }}
      VITE_AZURE_AD_REDIRECT_URI:             ${{ secrets.VITE_AZURE_AD_REDIRECT_URI }}
      VITE_AZURE_AD_POST_LOGOUT_REDIRECT_URI: ${{ secrets.VITE_AZURE_AD_POST_LOGOUT_REDIRECT_URI }}
      VITE_AZURE_AD_API_CLIENT_ID:            ${{ secrets.VITE_AZURE_AD_API_CLIENT_ID }}
      VITE_AZURE_AD_API_SCOPE_URI:            ${{ secrets.VITE_AZURE_AD_API_SCOPE_URI }}
      VITE_API_URL:                           ${{ secrets.VITE_API_URL }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js and cache dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      # Step 3: Install dependencies and build the app
      - name: Install & build
        working-directory: apps/admin-web
        run: |
          npm ci
          npm run build

      # Step 4: Deploy to Azure Static Web Apps
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Deployment token for your Static Web App (stored as a GitHub secret)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_APP_DEPLOY_KEY }}
          # GitHub token for commenting on PRs/status updates
          repo_token:                     ${{ secrets.PERSONAL_TOKEN }}
          action:                         upload
          app_location:                   apps/admin-web
          api_location:                   ''
          app_artifact_location:          dist
